version: '3.8'

services:
  eureka:
    build:
      context: eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ffp-network
  getaway:
    build:
      context: getaway
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    depends_on:
      eureka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8765/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - ffp-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  establishment:
    build:
      context: ./establishment
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - ffp-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  dish:
    build:
      context: ./dish
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8081/actuator/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - ffp-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  ordering:
    build:
      context: ./ordering
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      getaway:
        condition: service_healthy
      dish:
        condition: service_healthy
    networks:
      - ffp-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
networks:
  ffp-network: