eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8081
spring:
  application:
    name: dish
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:micro_dish;
    username: micro_dish_user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  profiles:
    active: testdata
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ffd-app

jwt:
  auth:
    converter:
      resource-id: ffp-client
      principle-attribute: preferred_username

