spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP